# from https://medium.com/@distillerytech/painless-travis-ci-cd-for-android-project-8c5bce253c4b
language: android
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
android:
#  licenses:
#    - 'android-sdk-preview-license-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
#before_script:
#  # Prepare pre-accepted licenses to not be promted at installation
#  - mkdir -p "$ANDROID_HOME/licenses"
#  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
script:
  - ./gradlew build check

#android:
#  components:
#    # Uncomment the lines below if you want to
#    # use the latest revision of Android SDK Tools
#    # - tools
#    # - platform-tools
#
#    # The BuildTools version used by your project
#    - build-tools-25.0.3
#
#    # The SDK version used to compile your project
#    - android-25
#
#    # Additional components
##    - extra-google-google_play_services
##    - extra-google-m2repository
##    - extra-android-m2repository
#
#    # Specify at least one system image,
#    # if you need to run emulator(s) during your tests
#    - sys-img-x86-android-25
##    - sys-img-armeabi-v7a-android-17
